# Playbook Exemplo 01
- name: Playbook de NGINX
  hosts: all
  tasks:
    - name: Remove o apache2
      package:
        name: apache2
        state: absent

    - name: Instala o nginx
      package:
        name: nginx
        state: present
