- name: instala agent Debian
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: instala agent RedHat
  yum:
    name: puppet-agent
    state: present
  when: ansible_os_family == "RedHat"

- name: inicia agente
  service:
    name: puppet
    state: started
    enabled: yes
