---
# tasks file for docker
- name: Install
  hosts: docker
  tasks:
    - name: Remove 
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker-io

